### ISSUE TITLE
Some questions in data_generator.py 

### ISSUE THREAD

**Issue by yyytiancai** [Chang-Chia-Chi/SaintPlus-Knowledge-Tracing-Pytorch#2]
Hello, Could tell me why u  remove the first item in content_ids, parts, task_container_ids and so on 【from line 79 to 84】
and remove the last item in answer_correct and user_answer？ 【in line 87 and line 89】
Thank u~I look forward to your answer.

        content_ids = content_ids[1:]
        parts = parts[1:]
        task_container_ids = task_container_ids[1:]
        time_lag = time_lag[1:]
        ques_elapsed_time = ques_elapsed_time[1:]
        label = answer_correct[1:] - 1
        label = np.clip(label, 0, 1)
        
        answer_correct = answer_correct[:-1]
        ques_had_explian = ques_had_explian[1:]
        user_answer = user_answer[:-1]

**Comment by Chang-Chia-Chi** [comment]
![image](https://user-images.githubusercontent.com/61031622/146157601-3ea059d0-976b-4568-b22b-aa1083393442.png)

It's original architecture in the paper below, I'll recommend to read and you'll know why it's needed.
https://arxiv.org/pdf/2010.12042.pdf

**Comment by yyytiancai** [comment]
您好，已收到。
