### ISSUE TITLE
数据生成问题data_generator

### ISSUE THREAD

**Issue by hongxiaDu** [Chang-Chia-Chi/SaintPlus-Knowledge-Tracing-Pytorch#3]
作者您好，请问一下，在data_generator.py文件里面，下面这几行代码，为什么answer_correct和user_answer是取第一个到倒数第二个的99个值，而其他的数据都是取第二个到最后一个总共99个值呢？如此，每个学生的做的题和它的answer_correct结果不就对不上了吗？本人初学者，没有明白此处的意义，还望不吝解答，谢谢~
        content_ids = content_ids[1:]
        parts = parts[1:]
        task_container_ids = task_container_ids[1:]
        time_lag = time_lag[1:]
        ques_elapsed_time = ques_elapsed_time[1:]
        label = answer_correct[1:] - 1
        label = np.clip(label, 0, 1)        
        answer_correct = answer_correct[:-1]
        ques_had_explian = ques_had_explian[1:]
        user_answer = user_answer[:-1]

**Comment by Chang-Chia-Chi** [comment]
https://github.com/Chang-Chia-Chi/SaintPlus-Knowledge-Tracing-Pytorch/issues/2

The purpose of this model is to predict whether student will answer question correctly based on his/her past experience. User's last answer & its correctness will provide some information about whether he/she'll crack the next problem. That's the reason why we need past answer sequence and embed it into the model.
